#!/bin/bash

cd invertedfs
rm datasets/out/part-r-00000
java -cp target/dependency/*:target/classes/ wdm.InvertedJob datasets/abstract1 datasets/abstract2 datasets/abstract3 datasets/out
  if [ -e "datasets/out/part-r-00000" ]; then
    echo "file exists!"
    less datasets/out/part-r-00000
  fi
fi 


