#!/bin/bash
cd giraph

FILE=triangles

hdfs dfs -rm /input/$FILE
hdfs dfs -copyFromLocal assets/$FILE /input/$FILE

echo "input is: "
hdfs dfs -cat /input/$FILE
hdfs dfs -rm -r /output/$FILE

hadoop jar /usr/local/giraph/giraph-examples/target/giraph-examples-1.2.0-SNAPSHOT-for-hadoop-2.5.1-jar-with-dependencies.jar org.apache.giraph.GiraphRunner wdm.TriangleComputation -vif org.apache.giraph.io.formats.IntIntNullTextInputFormat -vip /input/$FILE -vof org.apache.giraph.io.formats.IdWithValueTextOutputFormat -op /output/$FILE -w 1 -ca giraph.SplitMasterWorker=false

hdfs dfs -cat /output/triangles/part-m-00000 | less
